"""Creaciond e la base de datos

Revision ID: 08eaf4d947c7
Revises: 
Create Date: 2024-10-25 08:59:37.857559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08eaf4d947c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Documento',
    sa.Column('documentoId', sa.Integer(), nullable=False),
    sa.Column('firmaDigitalId', sa.Integer(), nullable=True),
    sa.Column('cddId', sa.String(length=50), nullable=False),
    sa.Column('nombreArchivo', sa.String(length=255), nullable=False),
    sa.Column('tipoDocumento', sa.String(length=50), nullable=False),
    sa.Column('versionDocumento', sa.Integer(), nullable=False),
    sa.Column('cantPaginas', sa.Integer(), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('firmado', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('documentoOrigenId', sa.Integer(), nullable=True),
    sa.Column('qrId', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('documentoId'),
    sa.UniqueConstraint('cddId')
    )
    op.create_table('DocumentoAuditoria',
    sa.Column('documentoAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('documentoId', sa.Integer(), nullable=False),
    sa.Column('firmaDigitalId', sa.Integer(), nullable=True),
    sa.Column('cddId', sa.String(length=50), nullable=False),
    sa.Column('nombreArchivo', sa.String(length=255), nullable=False),
    sa.Column('tipoDocumento', sa.String(length=50), nullable=False),
    sa.Column('versionDocumento', sa.Integer(), nullable=False),
    sa.Column('cantPaginas', sa.Integer(), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('hashTabla', sa.String(length=255), nullable=False),
    sa.Column('firmado', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('documentoOrigenId', sa.Integer(), nullable=True),
    sa.Column('qrId', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('documentoAuditoriaId')
    )
    op.create_table('DocumentoXMovimientoAuditoria',
    sa.Column('documentoXMovimientoAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('documentoXMovimientoId', sa.Integer(), nullable=False),
    sa.Column('movimientoId', sa.Integer(), nullable=False),
    sa.Column('documentoId', sa.Integer(), nullable=False),
    sa.Column('fechaAsociacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('foliosInicial', sa.Integer(), nullable=True),
    sa.Column('foliosFinal', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('documentoXMovimientoAuditoriaId')
    )
    op.create_table('EstadoExpediente',
    sa.Column('estadoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('nombreEstadoExpediente', sa.String(length=50), nullable=False),
    sa.Column('descripcionEstadoExpediente', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('estadoExpedienteId'),
    sa.UniqueConstraint('hashTabla'),
    sa.UniqueConstraint('nombreEstadoExpediente')
    )
    op.create_table('EstadoExpedienteAuditoria',
    sa.Column('estadoExpedienteAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioId', sa.Integer(), nullable=True),
    sa.Column('estadoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('nombreEstadoExpediente', sa.String(length=50), nullable=False),
    sa.Column('descripcionEstadoExpediente', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('estadoExpedienteAuditoriaId')
    )
    op.create_table('ExpedienteAuditoria',
    sa.Column('expedienteAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.Column('tipoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('expedientePadreId', sa.Integer(), nullable=True),
    sa.Column('numeroExpediente', sa.String(length=50), nullable=False),
    sa.Column('areaIniciadoraId', sa.Integer(), nullable=False),
    sa.Column('usuarioCreadorFisicoId', sa.Integer(), nullable=False),
    sa.Column('usuarioCreadorAplicacionId', sa.Integer(), nullable=False),
    sa.Column('asuntoExpediente', sa.String(length=255), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('fechaUltimoMovimiento', sa.TIMESTAMP(), nullable=True),
    sa.Column('visibilidadExpediente', sa.String(length=50), nullable=False),
    sa.Column('temaNombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.Column('areaActualidadId', sa.Integer(), nullable=True),
    sa.Column('foliosApertura', sa.Integer(), nullable=False),
    sa.Column('foliosActuales', sa.Integer(), nullable=True),
    sa.Column('documentoSiradId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('expedienteAuditoriaId')
    )
    op.create_table('ExpedienteXNormaAuditoria',
    sa.Column('expedienteXNormaAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('expedienteXNormaId', sa.Integer(), nullable=False),
    sa.Column('fechaAsociacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('normaId', sa.Integer(), nullable=False),
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('expedienteXNormaAuditoriaId')
    )
    op.create_table('HistorialEstadoExpedienteAuditoria',
    sa.Column('historialEstadoExpedienteAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('historialEstadoExpedienteId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estadoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.Column('fechaDesde', sa.TIMESTAMP(), nullable=False),
    sa.Column('fechaHasta', sa.TIMESTAMP(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('historialEstadoExpedienteAuditoriaId')
    )
    op.create_table('MovimientoAuditoria',
    sa.Column('movimientoAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('movimientoId', sa.Integer(), nullable=False),
    sa.Column('tramiteId', sa.Integer(), nullable=False),
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.Column('usuarioFisicoId', sa.Integer(), nullable=False),
    sa.Column('usuarioAplicacionId', sa.Integer(), nullable=False),
    sa.Column('areaOrigenId', sa.Integer(), nullable=False),
    sa.Column('areaDestinoId', sa.Integer(), nullable=True),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('observacionMovimiento', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('movimientoAuditoriaId')
    )
    op.create_table('NormaAuditoria',
    sa.Column('normaAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('normaId', sa.Integer(), nullable=False),
    sa.Column('tipoNormaId', sa.Integer(), nullable=False),
    sa.Column('numeroNorma', sa.String(length=50), nullable=False),
    sa.Column('descripcionNorma', sa.String(length=255), nullable=True),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('normaCddId', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('normaAuditoriaId')
    )
    op.create_table('Permiso',
    sa.Column('permisoId', sa.Integer(), nullable=False),
    sa.Column('nombrePermiso', sa.String(length=50), nullable=False),
    sa.Column('descripcionPermiso', sa.String(length=100), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('permisoId'),
    sa.UniqueConstraint('hashTabla')
    )
    op.create_table('PermisoAuditoria',
    sa.Column('permisoAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('permisoId', sa.Integer(), nullable=False),
    sa.Column('nombrePermiso', sa.String(length=50), nullable=False),
    sa.Column('descripcionPermiso', sa.String(length=100), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('permisoAuditoriaId')
    )
    op.create_table('Rol',
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.Column('nombreRol', sa.String(length=50), nullable=False),
    sa.Column('descripcionRol', sa.String(length=255), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.UniqueConstraint('hashTabla'),
    sa.PrimaryKeyConstraint('rolId')
    )
    op.create_table('RolXPermiso',
    sa.Column('rolXPermisoId', sa.Integer(), nullable=False),
    sa.Column('permisoId', sa.Integer(), nullable=False),
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['permisoId'], ['Permiso.permisoId'], ),
    sa.ForeignKeyConstraint(['rolId'], ['Rol.rolId'], ),
    sa.PrimaryKeyConstraint('rolXPermisoId'),
    sa.UniqueConstraint('hashTabla')
    )
    op.create_table('RolAuditoria',
    sa.Column('rolAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.Column('nombreRol', sa.String(length=50), nullable=False),
    sa.Column('descripcionRol', sa.String(length=255), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('rolAuditoriaId')
    )
    op.create_table('Usuario',
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('cuilUsuario', sa.String(length=50), nullable=True),
    sa.Column('nombreUsuario', sa.String(length=50), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechaBaja', sa.TIMESTAMP(), nullable=True),
    sa.Column('areaId', sa.Integer(), nullable=True),
    sa.Column('aplicacionVediId', sa.Integer(), nullable=True),
    sa.Column('apiKey', sa.String(length=100), nullable=True),
    sa.Column('usuarioAlta', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('usuarioId'),
    sa.UniqueConstraint('cuilUsuario'),
    sa.UniqueConstraint('hashTabla'),
    sa.UniqueConstraint('aplicacionVediId'),
    sa.UniqueConstraint('apiKey')
    )
    op.create_table('UsuarioAuditoria',
    sa.Column('usuarioAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('cuilUsuario', sa.String(length=50), nullable=True),
    sa.Column('nombreUsuario', sa.String(length=50), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechaBaja', sa.TIMESTAMP(), nullable=True),
    sa.Column('areaId', sa.Integer(), nullable=True),
    sa.Column('aplicacionVediId', sa.Integer(), nullable=True),
    sa.Column('apiKey', sa.String(length=100), nullable=True),
    sa.Column('usuarioAlta', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('usuarioAuditoriaId')
    )
    op.create_table('TipoExpediente',
    sa.Column('tipoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('nombreTipoExpediente', sa.String(length=50), nullable=False),
    sa.Column('descripcionTipoExpediente', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tipoExpedienteId'),
    sa.UniqueConstraint('hashTabla'),
    sa.UniqueConstraint('nombreTipoExpediente')
    )
    op.create_table('TipoExpedienteAuditoria',
    sa.Column('tipoExpedienteAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('tipoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('nombreTipoExpediente', sa.String(length=50), nullable=False),
    sa.Column('descripcionTipoExpediente', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tipoExpedienteAuditoriaId')
    )
    op.create_table('TipoNorma',
    sa.Column('tipoNormaId', sa.Integer(), nullable=False),
    sa.Column('nombreTipoNorma', sa.String(length=50), nullable=False),
    sa.Column('descripcionTipoNorma', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tipoNormaId'),
    sa.UniqueConstraint('hashTabla'),
    sa.UniqueConstraint('nombreTipoNorma')
    )
    op.create_table('TipoNormaAuditoria',
    sa.Column('tipoNormaAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('tipoNormaId', sa.Integer(), nullable=False),
    sa.Column('nombreTipoNorma', sa.String(length=50), nullable=False),
    sa.Column('descripcionTipoNorma', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tipoNormaAuditoriaId')
    )
    op.create_table('Expediente',
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.Column('tipoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('expedientePadreId', sa.Integer(), nullable=True),
    sa.Column('numeroExpediente', sa.String(length=50), nullable=False),
    sa.Column('areaIniciadoraId', sa.Integer(), nullable=False),
    sa.Column('usuarioCreadorFisicoId', sa.Integer(), nullable=False),
    sa.Column('usuarioCreadorAplicacionId', sa.Integer(), nullable=False),
    sa.Column('asuntoExpediente', sa.String(length=255), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechaUltimoMovimiento', sa.TIMESTAMP(), nullable=True),
    sa.Column('visibilidadExpediente', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.Column('areaActualidadId', sa.Integer(), nullable=True),
    sa.Column('foliosApertura', sa.Integer(), nullable=False),
    sa.Column('foliosActuales', sa.Integer(), nullable=True),
    sa.Column('documentoSiradId', sa.Integer(), nullable=True),
    sa.Column('temaNombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tipoExpedienteId'], ['TipoExpediente.tipoExpedienteId'], ),
    sa.PrimaryKeyConstraint('expedienteId'),
    sa.UniqueConstraint('numeroExpediente')
    )
    op.create_table('Norma',
    sa.Column('normaId', sa.Integer(), nullable=False),
    sa.Column('tipoNormaId', sa.Integer(), nullable=False),
    sa.Column('numeroNorma', sa.String(length=50), nullable=False),
    sa.Column('descripcionNorma', sa.String(length=255), nullable=True),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('normaCddId', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tipoNormaId'], ['TipoNorma.tipoNormaId'], ),
    sa.PrimaryKeyConstraint('normaId'),
    sa.UniqueConstraint('hashTabla'),
    sa.UniqueConstraint('numeroNorma')
    )
    op.create_table('ExpedienteXNorma',
    sa.Column('expedienteXNormaId', sa.Integer(), nullable=False),
    sa.Column('fechaAsociacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('normaId', sa.Integer(), nullable=False),
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expedienteId'], ['Expediente.expedienteId'], ),
    sa.ForeignKeyConstraint(['normaId'], ['Norma.normaId'], ),
    sa.PrimaryKeyConstraint('expedienteXNormaId')
    )
    op.create_table('HistorialEstadoExpediente',
    sa.Column('historialEstadoExpedienteId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estadoExpedienteId', sa.Integer(), nullable=False),
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.Column('fechaDesde', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fechaHasta', sa.TIMESTAMP(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estadoExpedienteId'], ['EstadoExpediente.estadoExpedienteId'], ),
    sa.ForeignKeyConstraint(['expedienteId'], ['Expediente.expedienteId'], ),
    sa.PrimaryKeyConstraint('historialEstadoExpedienteId')
    )
    op.create_table('Movimiento',
    sa.Column('movimientoId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tramiteId', sa.Integer(), nullable=False),
    sa.Column('expedienteId', sa.Integer(), nullable=False),
    sa.Column('usuarioFisicoId', sa.Integer(), nullable=False),
    sa.Column('usuarioAplicacionId', sa.Integer(), nullable=False),
    sa.Column('areaOrigenId', sa.Integer(), nullable=False),
    sa.Column('areaDestinoId', sa.Integer(), nullable=True),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('observacionMovimiento', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['expedienteId'], ['Expediente.expedienteId'], ),
    sa.ForeignKeyConstraint(['usuarioAplicacionId'], ['Usuario.usuarioId'], ),
    sa.ForeignKeyConstraint(['usuarioFisicoId'], ['Usuario.usuarioId'], ),
    sa.PrimaryKeyConstraint('movimientoId')
    )
    op.create_table('DocumentoXMovimiento',
    sa.Column('documentoXMovimientoId', sa.Integer(), nullable=False),
    sa.Column('movimientoId', sa.Integer(), nullable=False),
    sa.Column('documentoId', sa.Integer(), nullable=False),
    sa.Column('fechaAsociacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('foliosInicial', sa.Integer(), nullable=True),
    sa.Column('foliosFinal', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['documentoId'], ['Documento.documentoId'], ),
    sa.ForeignKeyConstraint(['movimientoId'], ['Movimiento.movimientoId'], ),
    sa.PrimaryKeyConstraint('documentoXMovimientoId')
    )
    op.create_table('RolXPermisoAuditoria',
    sa.Column('rolXPermisoAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('rolXPermisoId', sa.Integer(), nullable=False),
    sa.Column('permisoId', sa.Integer(), nullable=False),
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('rolXPermisoAuditoriaId')
    )
    op.create_table('RolXUsuario',
    sa.Column('rolXUsuarioId', sa.Integer(), nullable=False),
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['rolId'], ['Rol.rolId'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['Usuario.usuarioId'], ),
    sa.PrimaryKeyConstraint('rolXUsuarioId'),
    sa.UniqueConstraint('hashTabla')
    )
    op.create_table('RolXUsuarioAuditoria',
    sa.Column('rolXUsuarioAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('rolXUsuarioId', sa.Integer(), nullable=False),
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('rolXUsuarioAuditoriaId')
    )
    op.create_table('TipoNotificacion',
    sa.Column('tipoNotificacionId', sa.Integer(), nullable=False),
    sa.Column('nombreTipoNotificacion', sa.String(length=50), nullable=False),
    sa.Column('descripcionTipoNotificacion', sa.String(length=255), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tipoNotificacionId'),
    sa.UniqueConstraint('hashTabla')
    )
    op.create_table('Notificacion',
    sa.Column('notificacionId', sa.Integer(), nullable=False),
    sa.Column('usuarioNotificadoId', sa.Integer(), nullable=False),
    sa.Column('tipoNotificacionId', sa.Integer, nullable=False),
    sa.Column('descripcionNotificacion',sa.String(length=255), nullable=False),
    sa.Column('usuarioAfectadoId',sa.Integer(),nullable=True),
    sa.Column('leido',sa.Boolean(),nullable=False,server_default='false'),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('notificacionId'),
    sa.ForeignKeyConstraint(['usuarioNotificadoId'], ['Usuario.usuarioId'], ),
    sa.ForeignKeyConstraint(['tipoNotificacionId'],['TipoNotificacion.tipoNotificacionId'],),
    sa.UniqueConstraint('hashTabla')
    )
    op.create_table('NotificacionAuditoria',
    sa.Column('notificacionAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuariousuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('notificacionId', sa.Integer(), nullable=False),
    sa.Column('usuarioNotificadoId', sa.Integer(), nullable=False),
    sa.Column('tipoNotificacionId', sa.Integer, nullable=False),
    sa.Column('descripcionNotificacion',sa.String(length=255), nullable=False),
    sa.Column('usuarioAfectadoId',sa.Integer(),nullable=True),
    sa.Column('leido',sa.Boolean(),nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('notificacionAuditoriaId')
    )
    op.create_table('TipoNotificacionAuditoria',
    sa.Column('tipoNotificacionAuditoriaId', sa.Integer(), nullable=False),
    sa.Column('ipAddress', sa.String(length=20), nullable=True),
    sa.Column('hostName', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=100), nullable=True),
    sa.Column('fechaModificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('operacionRealizada', sa.String(length=100), nullable=False),
    sa.Column('usuarioResponsableId', sa.Integer(), nullable=True),
    sa.Column('usuariousuarioAplicacionResponsableId', sa.Integer(), nullable=True),
    sa.Column('tipoNotificacionId', sa.Integer(), nullable=False),
    sa.Column('nombreTipoNotificacion', sa.String(length=50), nullable=False),
    sa.Column('descripcionTipoNotificacion', sa.String(length=255), nullable=False),
    sa.Column('fechaCreacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('hashTabla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tipoNotificacionAuditoriaId')
    )
    op.execute(
        """
        CREATE EXTENSION IF NOT EXISTS pgcrypto;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DocumentoXMovimiento')
    op.drop_table('Movimiento')
    op.drop_table('HistorialEstadoExpediente')
    op.drop_table('ExpedienteXNorma')
    op.drop_table('Norma')
    op.drop_table('Expediente')
    op.drop_table('TipoNormaAuditoria')
    op.drop_table('TipoNorma')
    op.drop_table('TipoExpedienteAuditoria')
    op.drop_table('TipoExpediente')
    op.drop_table('PermisoAuditoria')
    op.drop_table('NormaAuditoria')
    op.drop_table('MovimientoAuditoria')
    op.drop_table('HistorialEstadoExpedienteAuditoria')
    op.drop_table('ExpedienteXNormaAuditoria')
    op.drop_table('ExpedienteAuditoria')
    op.drop_table('EstadoExpedienteAuditoria')
    op.drop_table('EstadoExpediente')
    op.drop_table('DocumentoXMovimientoAuditoria')
    op.drop_table('DocumentoAuditoria')
    op.drop_table('Documento')
    op.drop_table('RolXUsuarioAuditoria')
    op.drop_table('RolXUsuario')
    op.drop_table('RolXPermisoAuditoria')
    op.drop_table('RolXPermiso')
    op.drop_table('Permiso')
    op.drop_table('Notificacion')
    op.drop_table('NotificacionAuditoria')
    op.drop_table('TipoNotificacion')
    op.drop_table('TipoNotificacionAuditoria')
    op.drop_table('UsuarioAuditoria')
    op.drop_table('Usuario')
    op.drop_table('RolAuditoria')
    op.drop_table('Rol')
    # ### end Alembic commands ###
