"""Creacion de triggers y funciones para auditoria

Revision ID: 26b480b289d0
Revises: 2760f5278f6a
Create Date: 2024-10-25 09:00:51.818900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.databaseUtils import _read_sql_file



# revision identifiers, used by Alembic.
revision: str = '26b480b289d0'
down_revision: Union[str, None] = '2760f5278f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_functions_aud=_read_sql_file('funciones/logTablaAuditoria.sql')
    op.execute(sql_functions_aud)
    sql_triggers_aud=_read_sql_file('triggers/triggersTablaAuditoria.sql')
    op.execute(sql_triggers_aud)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_functions_aud=_read_sql_file('funciones/dropLogTablaAuditoria.sql')
    op.execute(sql_functions_aud)
    sql_triggers_aud=_read_sql_file('triggers/dropTriggersTablaAuditoria.sql')
    op.execute(sql_triggers_aud)
    # ### end Alembic commands ###