"""cracion procedimientos

Revision ID: 3f9496e0e01c
Revises: 26b480b289d0
Create Date: 2024-10-29 09:16:42.669314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.databaseUtils import _read_sql_file

# revision identifiers, used by Alembic.
revision: str = '3f9496e0e01c'
down_revision: Union[str, None] = '26b480b289d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_procedures=_read_sql_file('funciones/funcionesDocumentoXMovimiento.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesExpediente.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesMovimiento.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesDocumento.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesHistorialEstadoExpediente.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesTipoExpediente.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesEstadoExpediente.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesPermiso.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesUsuario.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesRol.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesRolXPermiso.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesNotificacion.sql')
    op.execute(sql_procedures)
    sql_procedures=_read_sql_file('funciones/funcionesRolXUsuario.sql')
    op.execute(sql_procedures)

    # Permiso procedimiento
    sql_permiso_procedure = _read_sql_file('funciones/verificarPermiso.sql')
    op.execute(sql_permiso_procedure)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_procedures=_read_sql_file('funciones/dropFunciones.sql')
    op.execute(sql_procedures)
