"""Funciones hash

Revision ID: 6bc1a8df2378
Revises: 3f9496e0e01c
Create Date: 2024-10-31 12:15:38.268630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.databaseUtils import _read_sql_file


# revision identifiers, used by Alembic.
revision: str = '6bc1a8df2378'
down_revision: Union[str, None] = '08eaf4d947c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_functions_hash=_read_sql_file('funciones/funcionHash.sql')
    op.execute(sql_functions_hash)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sql_funciones_hash=_read_sql_file('funciones/dropHashTabla.sql')
    op.execute(sql_funciones_hash)
    # ### end Alembic commands ###
