DROP FUNCTION IF EXISTS public."crearRelacion" (INT, INT, INT, INT, BOOLEAN, VARCHAR(100));
DROP FUNCTION IF EXISTS public."verificarPermiso" (INT, VARCHAR(100));
DROP FUNCTION IF EXISTS public."crearUsuario" (VARCHAR(50), INT, BOOLEAN, INT,VARCHAR(100));
DROP FUNCTION IF EXISTS public."crearMovimiento" (INT, INT, INT, INT, INT, INT, INT, TEXT, BOOLEAN);
DROP FUNCTION IF EXISTS public."crearExpediente" (INT, INT, VARCHAR(100), INT, INT, INT, VARCHAR(100), VARCHAR(100), BOOLEAN, VARCHAR(100), INT, INT,INT);
DROP FUNCTION IF EXISTS public."crearDocumento" (INT, VARCHAR(255), VARCHAR(50), INT, INT, BOOLEAN, BOOLEAN, VARCHAR(100));
DROP FUNCTION IF EXISTS public."obtenerTipoExpedientePorNombre" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."crearHistorialEstadoExpediente" (INT, INT, TIMESTAMP, BOOLEAN, VARCHAR(100));
DROP FUNCTION IF EXISTS public."obtenerEstadoExpedientePorNombre" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."obtenerEstadoExpedienteIdPorExpedienteId" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."obtenerFoliosActuales" (VARCHAR(50)); 
DROP FUNCTION IF EXISTS public."obtenerExpedientePorNumeroExpediente" (VARCHAR(100));
DROP FUNCTION IF EXISTS public."actualizarFoliosExpediente" (INT, INT);
DROP FUNCTION IF EXISTS public."actualizarAreaActualidadExpediente" (INT, INT);
DROP FUNCTION IF EXISTS public."obtenerExpedientePorId" (INT);
DROP FUNCTION IF EXISTS public."obtenerDocumentosPorExpedienteId" (INT);
DROP FUNCTION IF EXISTS public."obtenerNombreYCddIdDocumentosPorExpedienteId" (INT);
DROP FUNCTION IF EXISTS public."obtenerTipoExpedientes" ();
DROP FUNCTION IF EXISTS public."verificarExistenciaNumeroExpediente"(VARCHAR(100));
DROP FUNCTION IF EXISTS public."obtenerMovimientosPorExpedienteId" (INT);
DROP FUNCTION IF EXISTS public."obtenerDocumentoPorId" (INT);
DROP FUNCTION IF EXISTS public."obtenerExpedientes" (INT, INT);
DROP FUNCTION IF EXISTS public."obtenerUsuariosPorRol" (INT);
DROP FUNCTION IF EXISTS public."obternerPermisos" (INT, INT);
DROP FUNCTION IF EXISTS public."crearPermiso" (VARCHAR(50), VARCHAR(100));
DROP FUNCTION IF EXISTS public."obtenerPermisoPorId" (INT);
DROP FUNCTION IF EXISTS public."obtenerPermisos" (INT, INT);
DROP FUNCTION IF EXISTS public."obtenerPermisosPorNombre" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."eliminarPermiso" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."verficarPermisoUsuario" (INT, VARCHAR(100));
DROP FUNCTION IF EXISTS public."obtenerUsuarioPorCuil" (VARCHAR(100));
DROP FUNCTION IF EXISTS public."obtenerUsuarioPorAplicacionVediId" (INT);
DROP FUNCTION IF EXISTS public."verificarExistenciaUsuarioAplicacion" (INT, VARCHAR(100));
DROP FUNCTION IF EXISTS public."verificarExistenciaUsuario" (INT);
DROP FUNCTION IF EXISTS public."obtenerUsuarioPorId" (INT);
DROP FUNCTION IF EXISTS public."crearRol" (VARCHAR(50), VARCHAR(100), BOOLEAN);
DROP FUNCTION IF EXISTS public."obtenerRoles" (INT, INT);
DROP FUNCTION IF EXISTS public."obtenerRolPorId" (INT);
DROP FUNCTION IF EXISTS public."obtenerRolPorNombre" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."eliminarRolPorNombre" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."crearRelacionRolPermiso" (INT, INT);
DROP FUNCTION IF EXISTS public."obtenerRolXPermiso" (INT, INT);
DROP FUNCTION IF EXISTS public."obtenerPermisosPorNombreRols" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."obtenerUsuarios" (INT, INT);
DROP FUNCTION IF EXISTS public."crearUsuarioAplicacion" (VARCHAR(50), INT, INT, VARCHAR(100));
DROP FUNCTION IF EXISTS public."obtenerUsuarioRol" (VARCHAR(50));
DROP FUNCTION IF EXISTS public."crearUsuarioAdministrador" (VARCHAR(100), VARCHAR(100), INT, INT);
DROP FUNCTION IF EXISTS public."darBajaUsuarioAplicacion" (int);
DROP FUNCTION IF EXISTS public."crearUsuarioSuperAdmin" (VARCHAR(100), VARCHAR(100), INT);
DROP FUNCTION IF EXISTS public."crearNotificacionBaja" (INT, INT, VARCHAR(255));
DROP FUNCTION IF EXISTS public."validarPermisoUsuario" (int, int);
DROP FUNCTION IF EXISTS public."verificarExistenciaUsuarioPorCuil" (VARCHAR(100));
DROP FUNCTION IF EXISTS public."crearUsuario" (VARCHAR(50), VARCHAR(100), INT, INT, INT);
DROP FUNCTION IF EXISTS public."asignarRolAUsuario" (INT, VARCHAR(50));
DROP FUNCTION IF EXISTS public."eliminarRolXUsuarioPorRolId"(INT);
DROP FUNCTION IF EXISTS public."eliminarRolXUsuarioPorUsuarioId"(INT);
DROP FUNCTION IF EXISTS public."obtenerDocumentos"();
DROP FUNCTION IF EXISTS public."verificarSolicitudBaja"(INT);
DROP FUNCTION IF EXISTS public."eliminarRolXPermisoPorPermisoId"(INT);
